services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn social_media_api.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-db
          property: connectionString

databases:
  - name: social-media-db
    plan: free
